logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss} %clr(%-5level) %clr(%logger{36}){cyan} : %msg%n"

vom:
  jwt:
    access-token:
      secret: ${JWT_ACCESS_SECRET}
      expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:3600000} # 60 minutes
    refresh-token:
      secret: ${JWT_REFRESH_SECRET}
      expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 days
    cookie:
      secure: false

spring:
  servlet:
    multipart:
      max-file-size: 5MB